# Generated by Django 3.2.4 on 2021-07-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='categories',
        ),
    ]
 

 