# Generated by Django 3.2.5 on 2021-07-19 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='Run')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('correoe', models.CharField(max_length=50, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Numero de telefono')),
                ('mensaje', models.CharField(max_length=200, verbose_name='Mensaje')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
            ],
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ] 
    
