# Generated by Django 3.2.5 on 2021-07-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20210719_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Apellidos',
            new_name='apellidos',
        ),
    ]
 

 