# Generated by Django 3.2.5 on 2021-07-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_apellidos_contacto_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='apellidos',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
 
 