# Generated by Django 3.2.4 on 2021-07-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20210719_1226'),
        ('tienda', '0005_auto_20210719_1321'),
    ]

    operations = [
    ]
