# Generated by Django 3.2.4 on 2021-07-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_merge_0003_auto_20210719_1226_0005_auto_20210719_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacto',
        ),
    ]
